"""
Build the point-by-point response document and the JCIM cover letter.

Both are new documents rather than edits, so python-docx builds them directly.
Items still waiting on information from the authors are left in square brackets
so they are visible on the page rather than quietly missing.
"""

import docx
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

GAP = RGBColor(0xB0, 0x30, 0x00)


def new_doc():
    d = docx.Document()
    s = d.styles["Normal"]
    s.font.name = "Calibri"
    s.font.size = Pt(11)
    for sec in d.sections:
        sec.left_margin = sec.right_margin = Inches(1.0)
        sec.top_margin = sec.bottom_margin = Inches(0.9)
    return d


def para(d, text, bold=False, italic=False, space=6, align=None, size=None):
    p = d.add_paragraph()
    r = p.add_run(text)
    r.bold, r.italic = bold, italic
    if size:
        r.font.size = Pt(size)
    p.paragraph_format.space_after = Pt(space)
    if align:
        p.alignment = align
    return p


def gap(d, text):
    p = d.add_paragraph()
    r = p.add_run(text)
    r.font.color.rgb = GAP
    r.bold = True
    p.paragraph_format.space_after = Pt(6)
    p.paragraph_format.left_indent = Inches(0.25)
    return p


def item(d, n, comment, response):
    p = d.add_paragraph()
    p.add_run(f"{n}. ").bold = True
    r = p.add_run(comment)
    r.italic = True
    p.paragraph_format.space_after = Pt(3)
    p.paragraph_format.space_before = Pt(10)
    q = d.add_paragraph()
    q.add_run("Response. ").bold = True
    q.add_run(response)
    q.paragraph_format.space_after = Pt(6)
    q.paragraph_format.left_indent = Inches(0.25)


# --------------------------------------------------------------------------- #
# RESPONSE TO COMMENTS
# --------------------------------------------------------------------------- #

def response_doc():
    d = new_doc()
    para(d, "Response to Supervisor Comments, Second Draft", bold=True, size=14)
    para(d, "Negative-Class Design Reveals a Net-Charge Shortcut in Anti-Diabetic "
            "Peptide Prediction", italic=True, space=10)
    para(d, "Oliver McQuillan and Manish Chauhan. Prepared 6 October 2026.",
         space=14)
    para(d, "Every comment is reproduced in italics with the change made beneath "
            "it. Section numbers refer to the second draft. Four new supporting "
            "tables (S11 to S14) and one new main-text table (Table 5) carry the "
            "new analyses, and every number in them is regenerated by a named "
            "script rather than transcribed. Three items still need information "
            "from the authors and are marked in red.", space=14)

    para(d, "Priorities", bold=True, size=12, space=8)

    item(d, "P1", "Auditing and explicit refining of the positive set.",
         "Audited and reported rather than reduced, with the consequences "
         "measured. Grouping by containment with a 50% coverage floor, the 966 "
         "positives collapse to 577 families against 861 for the independently "
         "drawn negatives, so the class carries about 60% of its nominal sample "
         "size. The three largest families are regions of human preproinsulin at "
         "56, 55 and 32 members, and 141 positives (14.6%) are preproinsulin "
         "fragments of four residues or more against none of the 966 negatives. "
         "Twenty-one families straddle the published split, carrying 226 "
         "positives. This is new text in Section 2.1 with Table S12, and a new "
         "limitation in Section 3.6. The set was not reduced, because doing so "
         "would break comparability with the source dataset of Xie et al. and "
         "with the four predictors benchmarked here; instead the partition was "
         "rebuilt family-aware as a sensitivity arm (Table S14), which narrows "
         "the negative-class AUC gap from 0.180 to 0.074 while the gap in "
         "deployment error holds at 20.6 points against 36.5. Part of the AUC "
         "effect is an artefact of the split; the deployment effect is not."),

    item(d, "P2", "Disentangle negative-class composition from length and charge "
                  "with additional ablations.",
         "A six-arm ablation now does this (Table 5, methods in Section 2.3, "
         "results in Section 3.1). Arms B and C show length is not the driver: "
         "length-matching the published pool lifts AUC from 0.682 to 0.710 while "
         "its hard-negative false-positive rate gets worse rather than better, "
         "81.6% to 91.8%, or 79.6% once the positives are subsampled to the 303 "
         "negatives that pool can supply. Arms D and E isolate composition at "
         "matched length and differ by 0.03 in AUC but by 54 points in "
         "false-positive rate. Arm F matches length and charge together, driving "
         "the charge separability of the training classes from 0.804 to 0.507, "
         "chance, for 0.018 in AUC, and cutting hard-negative false positives "
         "from 45.1% to 33.1%. Arms C and D cannot reach 873 pairs because their "
         "source databases lack the lengths, which is reported as a finding "
         "rather than hidden. Every arm is a mean over ten training-row "
         "permutations, because row subsampling makes a single fit depend on row "
         "order by about 0.004 in AUC, the size of the smallest difference "
         "between arms. This result reversed Section 4.1 and the Conclusions: "
         "the first draft argued charge-matching was not worth forcing, and the "
         "data say otherwise."),

    item(d, "P3", "Repeat the prospective screen across the five ESM-2 seeds and "
                  "report selection stability.",
         "Set up but not yet run. The five seed adapters live on the Viking "
         "cluster and a job (phase5.8_seed_screen) has been written to score all "
         "3,596 candidates under each, which needs no retraining and no new "
         "embeddings, since the frozen vectors XGBoost consumes do not move with "
         "the seed. Section 4.3 meanwhile answers the deployment question "
         "directly, see comment 5 below."),
    gap(d, "Outstanding: the Viking job must be run before submission. Section "
           "3.3 and Section 4.3 have a place for its numbers.")

    para(d, "Detailed comments", bold=True, size=12, space=8)

    item(d, "1", "Clarify whether any short peptides in the test set share "
                 "identical or N-1 sub-sequences with the training set, and "
                 "discuss discovery against sequence extension. A supplementary "
                 "table of nearest training distance for the top leads would "
                 "strengthen the manuscript.",
         "Measured on both sides and added as two supporting tables. For the "
         "split (new paragraph in Section 2.1, Table S11): no test sequence "
         "occurs exactly in the training set; 67 of 178 (37.6%) stand in a "
         "substring relationship against a 20.9% residue-shuffled null holding "
         "length and composition fixed (200 shuffles, P < 0.005); 41 (23.0%) "
         "reach 80% identity, and they concentrate exactly where clustering did "
         "not reach, 35 of the 130 test sequences below 11 residues against 6 of "
         "the 48 above. Removing those 41 rows without refitting lowers test AUC "
         "from 0.877 to 0.831, so the split inflates discrimination by about "
         "0.046 and the manuscript now says so. Identity is normalised over the "
         "longer sequence of each pair, since CD-HIT's convention of normalising "
         "over the shorter saturates at 1.0 for any containment and is useless "
         "at these lengths. For the screen (Section 3.6, Table S13): 64 of the "
         "412 discoveries (15.5%) wholly contain a training positive of three "
         "residues or more and 41 (10.0%) one of six or more; 23 reach 80% "
         "identity and every one is in the short band the filter never covered, "
         "against none of the 196 long discoveries. The filter works where it "
         "applies, and where it does not, part of what the screen returns is "
         "motif extension rather than discovery. Table S13 is the requested lead "
         "table, giving the nearest training positive, its identity and any "
         "contained positive for the ten highest-scoring leads of each tier."),

    item(d, "2", "State explicitly in Section 2.5 whether cluster-level leakage "
                 "across the 5 cross-validation folds could overestimate the "
                 "out-of-fold calibration in Figure S5.",
         "Stated, and quantified rather than conceded. Section 2.5 now reports "
         "that 540 of the 1,754 training rows (30.8%, between 29.4% and 31.9% "
         "per fold) have a family relative in their own fold's training rows, "
         "that grouping the folds by family lowers out-of-fold AUC from 0.916 to "
         "0.896 and moves the swept threshold from 0.93 to 0.97, and that the "
         "consensus threshold inherits the same direction of bias because its "
         "ESM-2 half shares the identical fold assignment. It also notes which "
         "number is unaffected: the 86% test-set precision, measured on the "
         "cluster-wise held-out split. Section 3.6 carries the same figures as a "
         "limitation."),

    item(d, "3", "Add a sentence in Section 2.6 addressing whether backbone "
                 "flexibility was enabled during HADDOCK's semi-flexible "
                 "simulated annealing.",
         "Added to Section 2.6. The paragraph now states that the three fixed "
         "conformers set the starting point only, that semi-flexible annealing "
         "frees interface side chains in its second stage and the interface "
         "backbone in its third and fourth, that every peptide residue lies at "
         "the interface so each whole chain fell inside the semi-flexible "
         "segment, and therefore that the backbone of a reported pose is not the "
         "backbone that was built. Two factual corrections were made in the same "
         "section while checking this against the recovered run parameters: the "
         "peptides were defined passive rather than active, and HADDOCK's own "
         "accessibility filter retained nine of the 22 supplied receptor "
         "residues as active. Both were wrong in the first draft."),
    gap(d, "Outstanding: run.cns from the eight WeNMR jobs would let this be "
           "stated from the run's own parameter file rather than from the "
           "documented protocol plus the recovered job parameters.")

    item(d, "4", "Distinguish overall net charge from localised N-terminal "
                 "charge throughout Sections 3.2 and 3.4. Clarify confidence in "
                 "the pose given that three cationic non-binders outrank "
                 "Diprotin A, and expand on whether the absent N-terminal salt "
                 "bridge indicates a non-competitive mechanism or a protocol "
                 "limitation.",
         "Three changes. Section 3.2 now separates the two quantities "
         "explicitly: the classifier learns net charge summed over every "
         "ionisable side chain, whereas DPP-IV reads one protonated alpha-amino "
         "group at one atom in one position, a group every peptide substrate "
         "carries whatever its net charge, so the two are independent and the "
         "shortcut is a property of the negative class rather than a coarse "
         "version of the biology. Section 3.4 now bounds what the lead's total "
         "can carry: a function placing three confidently rejected peptides "
         "above a documented inhibitor is not ranking the panel by propensity to "
         "bind, so the lead's -100.1 is evidence of a large, shape-complementary, "
         "desolvating interface rather than of tighter binding than Diprotin A. "
         "Section 3.5 now gives both readings of the missing contact and says "
         "the data do not separate them: either the peptide occupies the cleft "
         "without presenting an amine for cleavage, which is a non-competitive "
         "or mixed mode, or the restraints reward buried area over a single salt "
         "bridge. It states that an inhibition assay reporting competition with "
         "substrate would settle it and that more docking would not."),

    item(d, "5", "In Section 4.3, mention whether freezing the head or using "
                 "fixed feature extraction with XGBoost or logistic regression "
                 "resolves the seed sensitivity while retaining ESM-2 "
                 "representations.",
         "Answered with a measurement, and the answer is yes. On the frozen "
         "1,287-dimensional vector, logistic regression is exactly deterministic "
         "across the five seeds at AUC 0.845 and XGBoost varies by 0.003 at "
         "0.860, against a 0.070 span for the fine-tune. Both sit inside the "
         "fine-tune's confidence interval and both keep the ESM-2 "
         "representation, so the seed sensitivity is a cost of the fine-tuning "
         "step rather than of the embedding. Section 4.3 now recommends frozen "
         "features with a convex head for any screen that needs a reproducible "
         "shortlist. It also notes that freezing the classification head itself "
         "is not an alternative, since an untrained head carries no mapping from "
         "representation to label and has to be fitted either way."),

    item(d, "6", "The dense clause in the Abstract should be split into two "
                 "concise sentences.",
         "Split. The clause is now three sentences: the negative-class result, "
         "then 'Architecture did not separate the learners.', then the two "
         "models and the stacking result. The Abstract was rewritten throughout "
         "to carry the ablation and remains within the 250 to 300 word range."),

    item(d, "7", "Update all pre-publication placeholders before submission.",
         "Not yet possible. The Supporting Information DOI, the repository URL, "
         "the ORCID, the corresponding author's email and the funding statement "
         "are still placeholders in the second draft, and your updated "
         "affiliation has not reached us."),
    gap(d, "Outstanding: ORCID, corresponding author email, funding statement, "
           "repository and data DOI, and the updated affiliation. These are the "
           "last blockers on submission.")

    item(d, "8", "Add a label or arrow on panel 8b targeting the orange sphere.",
         "Added. The sphere is now labelled 'free N-terminal amine' in the panel "
         "with an arrow pointing at it, and the caption says so and names the "
         "unmade 6.5 A approach to the Glu206 carboxylate. The panel is "
         "otherwise unchanged and keeps its pixel dimensions."),

    item(d, "9", "Ensure the text reiterates that the single-fit AUC of 0.877 is "
                 "the best-performing seed rather than the seed-ensemble mean of "
                 "0.842.",
         "Stated in both places. Section 3.1 now says the 0.877 carried in Table "
         "2 is the best of five and sits 0.035 above the five-seed mean reported "
         "beside it, that the two numbers are a single favourable fit and the "
         "distribution it came from rather than an estimate and its uncertainty, "
         "and that the adapter carried into the screen, the shortlist and the "
         "case study is that best-seed fit. The Table 2 caption now says the "
         "same."),

    item(d, "10", "Advise future workers against applying the ToxinPred2 and "
                  "AlgPred 2.0 binary cut-offs as hard filters on short "
                  "hydrolysate fragments.",
         "Added to Section 3.3. The text now states that neither cut-off should "
         "be used as a hard filter on short hydrolysate fragments, that at the "
         "published thresholds the two together would discard 93.0% of the "
         "discoveries of ten residues or fewer at a rate set by length rather "
         "than by sequence, that the Tier-1 lead carried forward is itself "
         "flagged at 0.54 against a 0.3 cut-off, and that the continuous scores "
         "should be kept as one ranking signal with exclusion deferred to "
         "assay."),

    para(d, "Journal scope and reproducibility", bold=True, size=12, space=8)
    para(d, "The framing note has been acted on in the Introduction and the "
            "cover letter. A new passage in the Introduction states that this is "
            "a study of how such datasets are built and scored rather than a "
            "search for new inhibitors, and that DPP-IV serves as a physical "
            "control system, chosen because its crystallographically "
            "characterised active site, documented peptide inhibitors and "
            "strongly anionic pocket make it possible to ask whether a "
            "structure-based score and a sequence classifier agree for the right "
            "reason. The transferable output is the set of rules in Section 4. "
            "The cover letter opens on the same point and states plainly that "
            "the docking is a control rather than the contribution.", space=8)
    para(d, "On reproducibility, every new analysis is produced by a named "
            "script and each new table names the script that generates it. The "
            "repository still needs to be made public and given a DOI before "
            "submission.", space=8)
    return d


# --------------------------------------------------------------------------- #
# COVER LETTER
# --------------------------------------------------------------------------- #

def cover_letter():
    d = new_doc()
    para(d, "[Date]", space=14)
    para(d, "The Editors", space=0)
    para(d, "Journal of Chemical Information and Modeling", space=14)
    para(d, "Dear Editors,", space=10)

    para(d, "We submit for your consideration “Negative-Class Design Reveals a "
            "Net-Charge Shortcut in Anti-Diabetic Peptide Prediction”, a "
            "methodological study of how bioactive-peptide classification "
            "datasets are built, scored and reported.", space=8)

    para(d, "The contribution is to dataset design and evaluation practice "
            "rather than to the discovery of any particular inhibitor. Holding "
            "the positives, hyperparameters and test set fixed and varying only "
            "the negative class moves discrimination by 0.219 in AUC and the "
            "false-positive rate on held-out proteome fragments from 93.3% to "
            "46.7%, where varying architecture across four learners, including a "
            "650M-parameter protein language model fine-tuned with DoRA, spans a "
            "range that contains a 20-feature amino-acid composition baseline, "
            "and where Bayesian hyperparameter optimisation moves the best tree "
            "learner by 0.011. A six-arm ablation then separates negative-class "
            "composition from the length and charge distributions it carries. "
            "Two arms differing by 0.03 in AUC differ by 54 points in "
            "false-positive rate, and under a family-aware split the "
            "best-scoring arm is the worst-deploying one, so a negative class "
            "selected on test AUC is selected backwards. Matching the negatives "
            "on net charge as well as length drives the residual shortcut to "
            "chance for 0.018 in AUC.", space=8)

    para(d, "DPP-IV and molecular docking enter this work as a physical control "
            "system, not as the object of study. We chose the target because its "
            "active site is crystallographically characterised, because "
            "documented peptide inhibitors are available as positive controls, "
            "and because the site is strongly anionic, which makes it possible "
            "to test whether a sequence classifier and a structure-based score "
            "agree for the right reason. They do not: net charge moves the two "
            "in opposite directions, and three peptides our classifier "
            "confidently rejected score above a documented inhibitor on "
            "electrostatics alone. The consequence is a reporting rule, that a "
            "hybrid screen should report the electrostatic share of every "
            "docking score rather than the total, and it is stated as such. We "
            "make no claim of a validated hit, and the peptides reported are "
            "described throughout as prioritised hypotheses for experimental "
            "follow-up.", space=8)

    para(d, "We are aware that the journal does not consider straightforward "
            "applications of docking to a single target without experimental "
            "validation. We believe this work falls outside that description: no "
            "result rests on the docking, the docking is itself one of the "
            "objects being measured, and its main role is to demonstrate a "
            "failure mode of hybrid in silico workflows that we then give a "
            "remedy for.", space=8)

    para(d, "The paper also reports against the state of the art. BertADP "
            "misclassified 92.4% of 328 Swiss-Prot fragments it had never seen, "
            "and the same failure appears in a deliberately weak control sharing "
            "its negative source, which locates the cause in the data rather "
            "than the architecture. We additionally quantify what our own "
            "partition is worth: near-duplicates inflate our headline AUC by "
            "about 0.046, cluster-level leakage across the cross-validation "
            "folds inflates the out-of-fold calibration by 0.020, and the "
            "positive class carries about 60% of its nominal sample size. All "
            "three are reported in the manuscript.", space=8)

    para(d, "All code, dataset splits, out-of-fold predictions, model weights "
            "and the scripts generating every table are available at [repository "
            "URL], archived at [DOI]. Each new supporting table names the script "
            "that produces it.", space=8)

    para(d, "The manuscript is original, is not under consideration elsewhere, "
            "and both authors have approved this version. We declare no "
            "competing financial interest.", space=14)

    para(d, "Yours sincerely,", space=10)
    para(d, "Manish Chauhan, on behalf of the authors", space=0)
    para(d, "School of Physics, Engineering and Technology, University of York, "
            "Heslington, York YO10 5DD, United Kingdom", space=0)
    para(d, "[email]", space=0)
    return d


if __name__ == "__main__":
    response_doc().save("ADP_response_to_comments_2nd_draft.docx")
    cover_letter().save("ADP_cover_letter_JCIM.docx")
    print("wrote the response document and the cover letter")
